<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
	  <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.27" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinSight.Usuario.Application\FinSight.Usuario.Application.csproj" />
    <ProjectReference Include="..\FinSight.Usuario.Domain\FinSight.Usuario.Domain.csproj" />
    <ProjectReference Include="..\FinSight.Usuario.Infrastructure\FinSight.Usuario.Infrastructure.csproj" />
  </ItemGroup>

</Project>
