<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
	</ItemGroup>


	<ItemGroup>
    <ProjectReference Include="..\FinSight.Usuario.Domain\FinSight.Usuario.Domain.csproj" />
    <ProjectReference Include="..\FinSight.Usuario.Infrastructure\FinSight.Usuario.Infrastructure.csproj" />
  </ItemGroup>

</Project>
