<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinSight.Metas.Application\FinSight.Metas.Application.csproj" />
    <ProjectReference Include="..\FinSight.Metas.Domain\FinSight.Metas.Domain.csproj" />
    <ProjectReference Include="..\FinSight.Metas.Infrastructure\FinSight.Metas.Infrastructure.csproj" />
  </ItemGroup>

</Project>
